# Inputs:
#   - Completed protein sequence
#   - List of residue indices that were generated by a model

import os
import esm
from esm.sdk.api import ESMProtein, GenerationConfig

class StructureEvaluator:
    def __init__(self, model_id, api_key=None):
        # Acquire API key from env var or constructor argument
        self.api_key = os.getenv("ESM_API_KEY", api_key)
        if not self.api_key:
            raise RuntimeError("ESM_API_KEY not provided or set in environment")

        # Initialize Forge client for the chosen ESM-3 model
        self.model = esm.sdk.client(model_id, token=self.api_key)

    def generate_structure(self, sequence, non_generated_indices, pdb_out="predicted_structure.pdb"):
        """
        Generate and evaluate predicted structure for a given sequence.

        Args:
            sequence (str): The complete protein sequence
            non_generated_indices (list[int]): Indices corresponding to given residues
            pdb_out (str): Output filename for predicted structure
        """

        # Create protein container and run structure generation
        protein = ESMProtein(sequence=sequence)
        protein = self.model.generate(
            protein,
            GenerationConfig(
                track="structure",  # generate 3D structure
                num_steps=10        # refinement rounds
            )
        )

        # Save predicted structure
        protein.to_pdb(pdb_out)

        # Extract pTM (scalar tensor → float)
        ptm = protein.ptm.item()

        # Extract per-residue pLDDT (1D tensor of shape [L])
        plddt = protein.plddt

        # Infer generated indices (complement of non-generated)
        all_indices = set(range(len(plddt)))
        generated_indices = list(all_indices - set(non_generated_indices))
        generated_indices.sort()

        # Compute mean pLDDT for generated residues
        generated_plddt = plddt[generated_indices]
        mean_generated_plddt = generated_plddt.mean().item()

        # Compute mean pLDDT for non-generated residues
        non_generated_plddt = plddt[non_generated_indices]
        mean_non_generated_plddt = non_generated_plddt.mean().item()

        return ptm, mean_generated_plddt, mean_non_generated_plddt